export const capacitySettings = {
    GET_CAPACITIES_STARTED: "GET_CAPACITIES_STARTED",
    GET_CAPACITIES_SUCCESS: "GET_CAPACITIES_SUCCESS",
    GET_CAPACITIES_FAILED: "GET_CAPACITIES_FAILED",
    CREATE_CAPACITY_STARTED: "CREATE_CAPACITY_STARTED",
    CREATE_CAPACITY_SUCCESS: "CREATE_CAPACITY_SUCCESS",
    CREATE_CAPACITY_FAILED: "CREATE_CAPACITY_FAILED",
    UPDATE_CAPACITY_STARTED: "UPDATE_CAPACITY_STARTED",
    UPDATE_CAPACITY_SUCCESS: "UPDATE_CAPACITY_SUCCESS",
    UPDATE_CAPACITY_FAILED: "UPDATE_CAPACITY_FAILED",
    DELETE_CAPACITY_STARTED: "DELETE_CAPACITY_STARTED",
    DELETE_CAPACITY_SUCCESS: "DELETE_CAPACITY_SUCCESS",
    DELETE_CAPACITY_FAILED: "DELETE_CAPACITY_FAILED"
};
