const capacityManagement = {
    CLEAR_CAPACITY_DATA: "CLEAR_CAPACITY_DATA",
    CLEAR_OPERATION_ERROR: "CLEAR_OPERATION_ERROR",
    
    GET_CAPACITY_STATUS_STARTED: "GET_CAPACITY_STATUS_STARTED",
    GET_CAPACITY_STATUS_SUCCESS: "GET_CAPACITY_STATUS_SUCCESS",
    GET_CAPACITY_STATUS_FAILED: "GET_CAPACITY_STATUS_FAILED",
    
    POLL_CAPACITY_STATUS_SUCCESS: "POLL_CAPACITY_STATUS_SUCCESS",
    
    START_CAPACITY_STARTED: "START_CAPACITY_STARTED",
    START_CAPACITY_SUCCESS: "START_CAPACITY_SUCCESS",
    START_CAPACITY_FAILED: "START_CAPACITY_FAILED",
    
    PAUSE_CAPACITY_STARTED: "PAUSE_CAPACITY_STARTED",
    PAUSE_CAPACITY_SUCCESS: "PAUSE_CAPACITY_SUCCESS",
    PAUSE_CAPACITY_FAILED: "PAUSE_CAPACITY_FAILED",
    
    GET_CAPACITY_RULES_STARTED: "GET_CAPACITY_RULES_STARTED",
    GET_CAPACITY_RULES_SUCCESS: "GET_CAPACITY_RULES_SUCCESS",
    GET_CAPACITY_RULES_FAILED: "GET_CAPACITY_RULES_FAILED",
    
    CREATE_CAPACITY_RULE_STARTED: "CREATE_CAPACITY_RULE_STARTED",
    CREATE_CAPACITY_RULE_SUCCESS: "CREATE_CAPACITY_RULE_SUCCESS",
    CREATE_CAPACITY_RULE_FAILED: "CREATE_CAPACITY_RULE_FAILED",
    
    UPDATE_CAPACITY_RULE_STARTED: "UPDATE_CAPACITY_RULE_STARTED",
    UPDATE_CAPACITY_RULE_SUCCESS: "UPDATE_CAPACITY_RULE_SUCCESS",
    UPDATE_CAPACITY_RULE_FAILED: "UPDATE_CAPACITY_RULE_FAILED",
    
    DELETE_CAPACITY_RULE_STARTED: "DELETE_CAPACITY_RULE_STARTED",
    DELETE_CAPACITY_RULE_SUCCESS: "DELETE_CAPACITY_RULE_SUCCESS",
    DELETE_CAPACITY_RULE_FAILED: "DELETE_CAPACITY_RULE_FAILED"
};

export default capacityManagement;