const settingsActionTypes =  {    
    SWITCH_TAB: "SWITCH_TAB",
    UPDATED_WORKSPACE: "UPDATED_WORKSPACE",
    RETRIEVED_WORKSPACES: "RETRIEVED_WORKSPACES",
    CANCELLED_WORKSPACE_CLIENT_MODIFIED: "CANCELLED_WORKSPACE_CLIENT_MODIFIED",
    WORKSPACE_CLIENT_MODIFIED: "WORKSPACE_CLIENT_MODIFIED",
    PERMISSIONS_CLIENT_MODIFIED: "PERMISSIONS_CLIENT_MODIFIED",
    RETRIEVED_POWERBI_OBJECT_LIST: "RETRIEVED_POWERBI_OBJECT_LIST",
    SELECTED_POWERBI_OBJECT: "SELECTED_POWERBI_OBJECT",
    PERMISSIONS_CHANGED: "PERMISSIONS_CHANGED"
};
export default settingsActionTypes;